### ISSUE TITLE
SDDM complains about missing QML components

### ISSUE THREAD

**Issue by K900** [nix-community/kde2nix#1]
Probably needs to be switched to Qt6 to be able to use new Breeze + Kirigami.

**Comment by Steinhagen** [comment]
The error messages when sddm starts are:

The current theme cannot be loaded due to the errors below, please select another theme.
file:///run/current-system/sw/share/sddm/themes/breeze/Main.qml: Library import requires a version
file:///run/current-system/sw/share/sddm/themes/breeze/Main.qml: Library import requires a version

**Comment by K900** [comment]
Fixed by not installing old Breeze.

**Comment by drzero42** [comment]
I'm also seeing these errors in sddm. All I've done is add the flake, load the nixos module and enable sddm and plasma6 services. I do not choose to install breeze anywhere else. Is this a regression or do I need to do anything specific to get a newer breeze?

**Comment by K900** [comment]
Are you using the latest version of the flake?

**Comment by drzero42** [comment]
@K900 Yes. I just added the flake and ran nixos-rebuild switch an hour ago.

**Comment by Steinhagen** [comment]
I've just updated my machine using the latest build and I'm unable to reproduce the issue. Everything works as expected for me.

**Comment by drzero42** [comment]
It could absolutely be an issue with my config. What kind of troubleshooting information can I provide to help figure this out?

**Comment by drzero42** [comment]
Can we start by verifying versions involved?

```
❯ readlink -f $(which sddm)
/nix/store/qlgpdgk7q32bfhvyii9s0zdgpmfn6ygm-sddm-0.20.0/bin/sddm

❯ readlink -f /run/current-system/sw/share/sddm/themes/breeze
/nix/store/ihzka2wfcwmbnz793ns8w5d22wawr6qb-plasma-workspace-5.91.0/share/sddm/themes/breeze
```

Are we on the same versions of sddm and the breeze theme?

**Comment by K900** [comment]
This is definitely wrong, your SDDM should be unstable-2023-12-something, the Qt6 build.

**Comment by drzero42** [comment]
Okay, now we are getting somewhere! :)
I am on NixOS 23.11 and have just enabled sddm with `services.xserver.displayManager.sddm.enable = true;`
I don't see anywhere in this flake that overrides the SDDM version?

**Comment by K900** [comment]
You should really be using unstable, we do not test this with 23.11 and probably never will.

**Comment by drzero42** [comment]
NixOS-unstable also appears to be on SDDM 0.20.0 - https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/display-managers/sddm/default.nix#L7

How are you guys getting the newer version?

**Comment by K900** [comment]
https://github.com/nix-community/kde2nix/blob/main/nixos/plasma6.nix#L263

**Comment by drzero42** [comment]
Ahh! I guess the code search on Github isn't that good, because searching for sddm in this repo did not find that line :facepalm: Thank you, I will try to troubleshoot why I am not getting this overlay :slightly_smiling_face:

**Comment by drzero42** [comment]
Okay, that hint helped a lot. I had a different nixpkgs overlay specified in my flake. A bit of fiddling around made sure the overlay from this flake gets applied, and I now have the Breeze theme in SDDM working! Thank you for your help, and great work on this repo! :smile:
