### ISSUE TITLE
Expanded view of Digital Clock statusbar plasmoid no longer shows additional time zones

### ISSUE THREAD

**Issue by jansol** [nix-community/kde2nix#13]
I have configured 4 additional time zones in the widget's settings (also removed and re-added them just in case, but that had no effect).

![image](https://github.com/nix-community/kde2nix/assets/2588851/d681e4e5-6810-4a5b-8d4f-697a17787b14)

A quick peek at the bugtracker suggests that https://bugs.kde.org/show_bug.cgi?id=477747 might be the related. Is the plasmoid maybe missing icu from its build deps?

**Comment by K900** [comment]
Upstream fix: https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/3646

Picked.
