### ISSUE TITLE
Cachix cache

### ISSUE THREAD

**Issue by baduhai** [nix-community/kde2nix#15]
It'd be great to have some cached packages, there's a lot to compile after all. Maybe a github runner to populate the cache automatically.

**Comment by K900** [comment]
I have most of it in my personal cache: 0uptime.cachix.org. I will probably set things up to push to the nix-community cachix once there's a little less churn.

**Comment by tsandrini** [comment]
+1 from me as well! :clap:

**Comment by K900** [comment]
https://github.com/nix-community/kde2nix/actions/runs/7445595376/job/20266991858 has a rough draft of a cache action. Any help with people more familiar with GHA would be appreciated.

**Comment by tsandrini** [comment]
> https://github.com/nix-community/kde2nix/actions/runs/7445595376/job/20266991858 has a rough draft of a cache action. Any help with people more familiar with GHA would be appreciated.

Thanks a lot! I haven't (yet) set up a personal cachix instance so I can confirm it from just what I've seen elsewhere. The action and the setup looks completely fine! I'd personally maybe try adding the DS magic cache 

```yaml
    - uses: DeterminateSystems/magic-nix-cache-action@v2
```

which could potentially help speed some things up (after the cachix action and before the build action). Apart from that looks fine to me.
