### ISSUE TITLE
kmailtransport-akonadi missing

### ISSUE THREAD

**Issue by jansol** [nix-community/kde2nix#16]
Needed for connecting to Exchange Web Services (Microsoft-hosted e-mail systems).

This seems to be also missing from upstream nixpkgs but this should be a convenient time to add it.

**Comment by K900** [comment]
Actually isn't kmailtransport it? I'm also pretty sure I've seen the Akonadi EWS resource being built.

**Comment by jansol** [comment]
Hmm, seems like it should Just Work unless it's broken. Will investigate later and reopen if I find something actionable.
