### ISSUE TITLE
kpartitionmanager is not feeling so well

### ISSUE THREAD

**Issue by jansol** [nix-community/kde2nix#18]
Main window shows up but everything is greyed out.

Likely related console output:
```
kf.coreaddons: "Could not find plugin kpmcore/"
Could not create instance of plugin   ""
Loaded backend plugin:  "pmsfdiskbackendplugin"
```

**Comment by K900** [comment]
c4223babe5e96077c8d6da5c775c84a89f8ac01b fixes most of it, with the caveat that kpartitionmanager needs to actually be installed system-wide, as it requires polkit actions and whatnot. The failure mode for "no polkit" is really bad though.
