### ISSUE TITLE
Moonlight doesn't launch

### ISSUE THREAD

**Issue by anthr76** [nix-community/kde2nix#26]
Moonlight installed from nixpkgs-unstable shows in log:

```
moonlight
00:00:00 - SDL Info (0): Compiled with SDL 2.28.4
00:00:00 - SDL Info (0): Running with SDL 2.28.4
00:00:00 - Qt Info: No translation available for "en_US"
00:00:00 - SDL Info (0): Detected Wayland
00:00:01 - Qt Warning: QQmlApplicationEngine failed to load component
00:00:01 - Qt Warning: qrc:/gui/main.qml:220:13: Type ToolBar unavailable
00:00:01 - Qt Warning: file:///nix/store/9wvh81p98ffj4v9ibww57zy1s2rn3i4s-qtquickcontrols2-5.15.11-bin/lib/qt-5.15.11/qml/QtQuick/Controls.2/Material/ToolBar.qml:40:1: invalid version auto, expected <major>.<minor>
```

I assume this is because it's built with qt5? Not sure if I should go to moonlight with this issue although it seems they support qt6.

**Comment by anthr76** [comment]
Via Matrix we discovered `QML2_IMPORT_PATH` allows moonlight to launch. Still looking into the rootcause

**Comment by K900** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/281486

**Comment by K900** [comment]
The fix should have made it to all channels, closing.

**Comment by anthr76** [comment]
Confirmed this is working now. Thanks!
