### ISSUE TITLE
Lock screen showing PKCS#11 error and referring to smart cards and fingerprint when neither have been set up

### ISSUE THREAD

**Issue by sreehax** [nix-community/kde2nix#36]
I have filed a KDE bug here: [https://bugs.kde.org/show_bug.cgi?id=479964](https://bugs.kde.org/show_bug.cgi?id=479964). I'm filing an issue here too, because I'm not 100% sure if this is a bug in KDE or possibly some issue with the flake itself.

**Comment by anthr76** [comment]
Same here. I'm assuming this is because I have PKCS#11 setup with tpm2 and yubikey

**Comment by K900** [comment]
It's not, I just don't think the lockscreen can actually tell if the hardware is available.

**Comment by sreehax** [comment]
I have received a response on my KDE bug report which suggests that the error is likely caused by a new PAM configuration required for Plasma 6 which may not be covered entirely by the flake.

[https://community.kde.org/Plasma/Plasma_6.0_Release_notes#New_required_PAM_configuration](
https://community.kde.org/Plasma/Plasma_6.0_Release_notes#New_required_PAM_configuration)
[https://invent.kde.org/plasma/kscreenlocker/-/merge_requests/163](https://invent.kde.org/plasma/kscreenlocker/-/merge_requests/163)

**Comment by K900** [comment]
Please do not file bug reports upstream until you have at least checked in with the distribution maintainers (in this case, me). I am aware of the situation, and will look into it.

**Comment by jansol** [comment]
I don't have any yubikey etc set up and I still see the message. I am curious about how to set one up for this though.
