### ISSUE TITLE
kdsoap-related Build Error

### ISSUE THREAD

**Issue by HippieMitch** [nix-community/kde2nix#41]
With flake.lock updated on 01/23/2024 @ 02:54 GMT I am getting the following build error.

![kdsoap](https://github.com/nix-community/kde2nix/assets/72957198/20e67556-85f9-4062-b2ef-b246e72f3dea)

It looks related to c52b71e.

The full log is here: 
[log.txt](https://github.com/nix-community/kde2nix/files/14017796/log.txt)

**Comment by K900** [comment]
Fixed in nixpkgs, wait for channels to update.

**Comment by HippieMitch** [comment]
Thanks!
